FROM openjdk:11-jdk-slim

LABEL maintainer="osman"

WORKDIR /app/source

COPY . .

RUN chmod +x mvnw && \
    ./mvnw clean package -Dspring.profiles.active=build && \
    mv ./target/*.jar app.jar

EXPOSE 8084

ENTRYPOINT ["java", "-jar", "app.jar"]
