FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 8501

# Backend service URL (Docker DNS)
ENV API_URL=http://be-app:8080

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
